Clean up some Throwables (#6157)
* Remove unnecessary UnsatisfiedLinkError and NoClassDefFoundError
  catches (added in #925 and #1644 to address issues before the reliance
  on the UEH), relying on the AccumuloUncaughtExceptionHandler (UEH)
  instead for MinorCompactor
* Rename incorrectly named internal LocalityGroupConfigurationError to
  LocalityGroupConfigurationException
* Replace `new Error` with `new IllegalStateException` for critical
  threads
* Make TabletServerLogger.startLogMaker use a critical thread instead of
  a fixed size thread pool, removing dead code and being more specific
  with exceptions
* Make critical thread halt logic the same as for the UEH, best effort
  to see the error message (like showing the thread id and flushing
  STDERR)
* Remove Error catch from tserver.tablet.Tablet and clean up some
  exception handling, deleting some throws statements for exceptions not
  thrown in the implementation
* (trivial) fix typo in UEH comment
* (trivial) remove unused logger in EventQueue